#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — provision the credential and ceiling that issue #7 asks for.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Never let a key land in a tracked file. .env is NOT gitignored in this repo.
ENV_FILE=".ci-facts.local.env"

REPO="MalcolmMcNeely/skills-marketplace"
WORKFLOW="paid-harness.yml"

banner "CI credentials and spend ceiling (issue #7)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "A workspace of its own"
say "The key must be metered, capped and revocable on its own, so it gets its"
say "own workspace rather than sharing the default one."
open_url "https://platform.claude.com/settings/workspaces"
step "Create a workspace. Suggested name: skills-marketplace-ci"
step "Open it and copy its ID from the address bar (starts wrkspc_)."
ask CI_WORKSPACE_NAME "Workspace name you used:"
ask CI_WORKSPACE_ID "Workspace ID (wrkspc_...), or leave blank:"
write_env CI_WORKSPACE_NAME "$CI_WORKSPACE_NAME"
[[ -n "$CI_WORKSPACE_ID" ]] && write_env CI_WORKSPACE_ID "$CI_WORKSPACE_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The ceiling"
say "Issue #11 fixed 100 dollars a month as an ALERT, not a hard stop, because"
say "a ledger that trips mid-pass wastes the whole pass."
note "Settings > Workspaces > $CI_WORKSPACE_NAME > Limits tab"
open_url "https://platform.claude.com/settings/workspaces"
step "Open the workspace, then the Limits tab."
step "Select 'Add notification' and set an email alert at \$100."
warn "A workspace spend limit can only be LOWER than the organisation limit."
if confirm "Also set a hard 'Change Limit' spend cap, above the alert, as a runaway backstop?"; then
  step "Select 'Change Limit' and set the cap."
  ask CI_HARD_LIMIT_USD "Hard spend limit you set, in dollars:"
  write_env CI_HARD_LIMIT_USD "$CI_HARD_LIMIT_USD"
else
  note "No hard cap. The alert is the only monthly control."
  write_env CI_HARD_LIMIT_USD "none"
fi
write_env CI_ALERT_USD "100"
pause "Alert set?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The API key"
say "An API key, not a subscription token. It is billed per token and can be"
say "revoked without touching your own login."
open_url "https://platform.claude.com/settings/keys"
step "Create Key. Name it skills-marketplace-ci."
step "Scope it to the $CI_WORKSPACE_NAME workspace, NOT the default one."
step "Copy the key. It is shown once."
ask_secret CI_API_KEY "Paste the key (hidden):"
if [[ -z "$CI_API_KEY" ]]; then
  warn "No key entered. Nothing to store."
  SKIPPED+=("the API key and the GitHub secret")
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The GitHub secret"
say "The workflow reads secrets.ANTHROPIC_API_KEY. The name must match exactly."
if [[ -n "$CI_API_KEY" ]]; then
  set_secret ANTHROPIC_API_KEY "$CI_API_KEY"
  unset CI_API_KEY
else
  note "Skipped: no key was entered in the previous stage."
fi
note "Check it landed:  gh secret list --repo $REPO"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Prove CI can reach claude"
say "workflow_dispatch only appears for workflows on the default branch."
say "This one is already on main, so the button exists."
if ! gh workflow list --repo "$REPO" | grep -q "$WORKFLOW"; then
  warn "$WORKFLOW is not on main yet. Push it, then re-run this stage."
fi

if confirm "Dispatch the smoke run now? It costs a few cents."; then
  if gh workflow run "$WORKFLOW" --repo "$REPO" -f mode=smoke; then
    say "Dispatched. Waiting for the run to register..."
    sleep 8
    RUN_ID="$(gh run list --repo "$REPO" --workflow "$WORKFLOW" --limit 1 \
      --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)"
    if [[ -n "$RUN_ID" ]]; then
      gh run watch --repo "$REPO" "$RUN_ID" || true
      say "The cost is on the 'cost, usd' line of the smoke step:"
      note "  gh run view --repo $REPO $RUN_ID --log | grep -A1 'cost, usd'"
    else
      warn "Could not find the run. Look at the Actions tab."
    fi
    say "Put the version, the runner image and that cost on issue #7."
  else
    warn "Dispatch failed. Is the workflow on main yet?"
    SKIPPED+=("dispatching the smoke run: gh workflow run $WORKFLOW --repo $REPO -f mode=smoke")
  fi
else
  SKIPPED+=("dispatching the smoke run: gh workflow run $WORKFLOW --repo $REPO -f mode=smoke")
fi

finish
